[tasks.dev]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.buildlinux]
env = { "CC_x86_64_unknown_linux_musl" = "x86_64-linux-musl-gcc" }
command = "cargo"
args = ["build", "--release", "--target=x86_64-unknown-linux-musl"]
dependencies = ["clean"]
